apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.example.com
spec:
  group: example.com
  names:
    kind: Workflow
    plural: workflows
    singular: workflow
    shortNames:
      - wf
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                definition:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
